vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        imagesAvatar:
            uri_prefix: /images/usuarios
            upload_destination: '%kernel.project_dir%/public/images/usuarios'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
